spring.application.name=eureka-server
server.port=8761

# Ne pas s'enregistrer auprès de lui-même
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Évite de garder en cache des microservices arrêtés pendant les tests localement
eureka.server.enable-self-preservation=false