spring.application.name=user_service
server.port=8081
# Connexion SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=MisfatDB;user=sa;password=Misfat2026&;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=Misfat2026&
# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=farah.zwawi06@gmail.com
# Ce n'est pas ton vrai mot de passe Gmail, c'est un mot de passe d'application généré dans ton compte Google
spring.mail.password=abcd efgh ijkl mnop
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Configuration du Client Eureka (Pointe vers le port du serveur créé à l'étape 1)
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# 5. Configuration de l'API Keycloak Admin (Utilisée par KeycloakService)
keycloak.auth-server-url=http://localhost:8080
keycloak.realm=misfat-realm
keycloak.client-id=misfat-admin-client
keycloak.client-secret=brecybVbPYgzOoOWXxczI7zY7KAMOixQ