# =========================================================================
# 1. CONFIGURATION DU SERVEUR
# =========================================================================
# On change le port à 8082 pour ne pas entrer en conflit avec le port 8081 du user_service
server.port=8082
spring.application.name=emission-service

# =========================================================================
# 2. CONFIGURATION DE LA BASE DE DONNÉES (MS SQL SERVER)
# =========================================================================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=MisfatDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Misfat2026&
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Configuration JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# =========================================================================
# 3. CONFIGURATION DU CLIENT EUREKA
# =========================================================================
# Pour que le nouveau service s'enregistre lui aussi sur le même serveur Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true